import bcrypt from "bcryptjs";

/**
 * Password hashing service backed by bcrypt.
 * Mirrors the Spring Boot `BCryptPasswordEncoder` behaviour so hashes
 * generated by either backend are interchangeable.
 */

const SALT_ROUNDS = 10;

/** Hash a plain-text password. */
export async function hashPassword(plain: string): Promise<string> {
  return bcrypt.hash(plain, SALT_ROUNDS);
}

/** Compare a plain-text password against a stored bcrypt hash. */
export async function comparePassword(
  plain: string,
  hash: string
): Promise<boolean> {
  return bcrypt.compare(plain, hash);
}
